name: Traffic to Badge

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC
  workflow_dispatch:

jobs:
  traffic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: yi-Xu-0100/traffic-to-badge@main
        with:
          my_token: ${{ secrets.TRAFFIC_TOKEN }}
          static_list: 'anishharis/session-tree'
          traffic_branch: traffic
          views_color: blue
          clones_color: blue
